### PR TITLE
5 showcase quarto extensions for the julia community

### PR DESCRIPTION
**Pull request by pat-alt**
cc @kellertuer

### CODE REVIEW

**Comment by pat-alt** [comment]
cc @kellertuer 

- [ ] add note on rendering to "Getting started" slide

**Comment by kellertuer** [comment]
I finished most of my work in the Documenter section;

*  I would like to have on one slide a `. . .` within a column (Workflow II) but was not able to get that to work (there is a marker in the slides
* I added a logo for Manopt to the title page of the documenter section, feel free to unify that
* the general workflow example code scrolls, that is fine with me though, because the story works with the beginning alone as well.

Besides the points above I took a note to add
* [ ] maybe outlook runnable code?

**Comment by pat-alt** [comment]
@kellertuer think this is ready to be merged (added a link to the PDF on the website)

**Comment by kellertuer** [comment]
Yes, I could not pull this (WiFi here); but I could download the pdf here and checked it – yes all looks great!

**Pull request merged**
